<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>PortfolioWeb.Api</RootNamespace>
</PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\PortfolioWeb.Application.Contract\PortfolioWeb.Application.Contract.csproj" />
        <ProjectReference Include="..\PortfolioWeb.Application\PortfolioWeb.Application.csproj" />
        <ProjectReference Include="..\PortfolioWeb.Core.Contracts\PortfolioWeb.Core.Contracts.csproj" />
        <ProjectReference Include="..\PortfolioWeb.Infrastructure\PortfolioWeb.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.0" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
        <PackageReference Include="Microsoft.OpenApi" Version="2.7.5" />
        <PackageReference Include="Scalar.AspNetCore" Version="2.4.4" />
    </ItemGroup>

</Project>
